[manifest]
version = "1.0.0"
priority = 0

# Inject Royal Sort into the built-in sorting method
[[patches]]
[patches.pattern]
target = 'cardarea.lua'
pattern = '''
elseif self.config.sort == 'asc' then
'''
position = 'before'
payload = '''
elseif self.config.sort == 'royal' then
G.FUNCS.ROYAL_SORT()
'''
match_indent = true


